### ISSUE TITLE
Publish package on Atmosphere

### ISSUE THREAD

**Issue by brylie** [apinf/apinf-accounts-fiware#10]
Now that we have a 0.1.0 version ready, lets publish this package on Atmosphere. Then, we can incorporate the package into APInf.

Note: we will need to make a GitHub (issue #11) release *after* publishing to Atmosphere, since small change(s) is/are made to the code when running `meteor publish`.

**Comment by mauriciovieira** [comment]
https://atmospherejs.com/apinf/accounts-fiware
