### ISSUE TITLE
Make 0.1.0 release

### ISSUE THREAD

**Issue by brylie** [apinf/apinf-accounts-fiware#11]
Once we have reached the 0.1.0 milestone (including publishing 0.1.0 to Atmosphere - #10), we can make a GitHub release:

https://github.com/apinf/apinf-accounts-fiware/releases

For some reason, publishing the package on Atmosphere changes the project metadata, requiring one more commit to track. For this reason, if it still stands, we should make the GitHub release immediately *after* publishing to Atmosphere.

**Comment by mauriciovieira** [comment]
https://github.com/apinf/apinf-accounts-fiware/releases/tag/v0.1.1
